import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import './ComplianceReport.css';

export default function ComplianceReport() {

    const navigate = useNavigate();
    const [reports, setReports] = useState([]);

    const fetchReports = () => {
        fetch("http://localhost:4000/api/reports")
            .then(res => res.json())
            .then(data => setReports(data))
            .catch(err => console.log(err));
    };

    useEffect(() => {
        fetchReports();
        
        const interval = setInterval(fetchReports, 3000);
        return () => clearInterval(interval);
    }, []);

    return (
        <div className='compliance-report'>

            <div className="page-header">
                <span>Compliance Reports</span>
            </div>

            <div className='compliance-content'>

                <div className='card'>
                    <h3>Access Review Report</h3>
                    <p>Summary of user roles and privilege distribution</p>
                    <button onClick={() => navigate('/generate')}>
                        Generate
                    </button>
                </div>

                <div className='card2'>
                    <h3>Audit Log Report</h3>
                    <p>Detailed record of policy breaches and control failures</p>
                    <button onClick={() => navigate('/generate')}>
                        Generate
                    </button>
                </div>

                <div className='card3'>
                    <h3>Compliance Scorecard</h3>
                    <p>Visual dashboard of compliance status and trends</p>
                    <button onClick={() => navigate('/generate')}>
                        Generate
                    </button>
                </div>

            </div>

            {/* Filter Section */}
            <div className='filter-section'>
                <h4>Filter</h4>
                <div className='filter-row'>

                    <div>
                        <label>Date Range</label>
                        <input type='date' />
                    </div>

                    <div>
                        <label>Department</label>
                        <select>
                            <option value='hr'>HR</option>
                            <option value='finance'>Finance</option>
                            <option value='it'>IT</option>
                        </select>
                    </div>

                    <div>
                        <label>Severity</label>
                        <select>
                            <option value=''>All Severities</option>
                            <option value='low'>Low</option>
                            <option value='medium'>Medium</option>
                            <option value='high'>High</option>
                        </select>
                    </div>

                </div>
            </div>

            {/* Reports Table */}
            <div className="reports-section">
                <h4>Generated Reports</h4>

                <table>
                    <thead>
                        <tr>
                            <th>Report Name</th>
                            <th>Generated By</th>
                            <th>Date</th>
                            <th>Format</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        {reports.length > 0 ? (
                            reports.map((report) => (
                                <tr key={report._id}>
                                    <td>{report.report}</td>
                                    <td>{report.generatedBy}</td>
                                    <td>{new Date(report.date).toLocaleDateString()}</td>
                                    <td>{report.format}</td>
                                    <td>{report.status}</td>
                                    <td>
                                        <button>Download</button>
                                    </td>
                                </tr>
                            ))
                        ) : (
                            <tr>
                                <td colSpan="6" style={{ textAlign: "center" }}>
                                    No Reports Found
                                </td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>

        </div>
    );
}