import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import './AuditLogs.css';

export default function ManageLogs() {
  const navigate = useNavigate();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(false);

  const fetchReports = () => {
    fetch("http://localhost:4000/api/reports")
      .then(res => res.json())
      .then(data => setReports(data))
      .catch(err => console.log(err));
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const handleDelete = async (id) => {
    if (window.confirm("Are you sure you want to delete this log?")) {
      setLoading(true);
      try {
        const res = await fetch(`http://localhost:4000/api/reports/${id}`, {
          method: 'DELETE',
          headers: { 'Content-Type': 'application/json' }
        });

        if (res.ok) {
          alert('Log deleted successfully');
          fetchReports();
        } else {
          alert('Failed to delete log');
        }
      } catch (err) {
        console.error(err);
        alert('Error deleting log');
      } finally {
        setLoading(false);
      }
    }
  };

  const handleDeleteAll = async () => {
    if (window.confirm("Are you sure you want to delete ALL logs? This cannot be undone!")) {
      setLoading(true);
      try {
        const res = await fetch('http://localhost:4000/api/reports/delete/all', {
          method: 'DELETE',
          headers: { 'Content-Type': 'application/json' }
        });

        if (res.ok) {
          alert('All logs deleted successfully');
          fetchReports();
        } else {
          alert('Failed to delete all logs');
        }
      } catch (err) {
        console.error(err);
        alert('Error deleting all logs');
      } finally {
        setLoading(false);
      }
    }
  };

  return (
    <div className="admin-container">
      <div className="sidebar">
        <h2>Privilege Guardian</h2>
        <ul>
          <li onClick={() => navigate('/admin')}>Dashboard</li>
          <li onClick={() => navigate('/audit')}>User Management</li>
          <li onClick={() => navigate('/compliancereport')}>Audit Logs</li>
          <li onClick={() => navigate('/manage-logs')} style={{ fontWeight: 'bold', color: '#ff6b6b' }}>Manage Logs</li>
          <li onClick={() => navigate('/attack')}>Simulation</li>
        </ul>
      </div>

      <div className="main-content">
        <div className="top-bar">
          <h1>Manage Audit Logs</h1>
          <button 
            onClick={handleDeleteAll} 
            disabled={loading}
            style={{ backgroundColor: '#ff6b6b' }}
          >
            {loading ? 'Deleting...' : 'Delete All Logs'}
          </button>
        </div>

        <div className="table-section">
          <h2>All Logs</h2>
          {reports.length > 0 ? (
            <table>
              <thead>
                <tr>
                  <th>Report Name</th>
                  <th>Generated By</th>
                  <th>Date</th>
                  <th>Format</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {reports.map((report) => (
                  <tr key={report._id}>
                    <td>{report.report}</td>
                    <td>{report.generatedBy}</td>
                    <td>{new Date(report.date).toLocaleDateString()}</td>
                    <td>{report.format}</td>
                    <td>{report.status}</td>
                    <td>
                      <button
                        onClick={() => handleDelete(report._id)}
                        disabled={loading}
                        style={{
                          backgroundColor: '#ff6b6b',
                          color: 'white',
                          border: 'none',
                          padding: '8px 12px',
                          cursor: loading ? 'not-allowed' : 'pointer',
                          borderRadius: '4px'
                        }}
                      >
                        Delete
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : (
            <p style={{ textAlign: 'center', marginTop: '20px' }}>No logs found</p>
          )}
        </div>
      </div>
    </div>
  );
}
