import { useState, useEffect } from 'react'
import { api } from '../utils/api'
import { Table, Spinner, Btn, Modal, Input, Select } from '../components/UI'
import { format } from 'date-fns'

export default function Reports({ addToast }) {
  const [reports, setReports] = useState([])
  const [loading, setLoading] = useState(true)
  const [modal, setModal] = useState(false)
  const [form, setForm] = useState({ name: '', format: 'PDF', generatedBy: '' })
  const [saving, setSaving] = useState(false)

  const load = async () => {
    try {
      const data = await api.getReports()
      setReports(data)
    } finally { setLoading(false) }
  }

  useEffect(() => { load() }, [])

  const create = async () => {
    if (!form.name || !form.generatedBy) { addToast('Fill all fields', 'warn'); return }
    setSaving(true)
    try {
      await api.createReport(form)
      addToast('Report created')
      setModal(false)
      setForm({ name: '', format: 'PDF', generatedBy: '' })
      load()
    } catch (e) { addToast(e.message || 'Failed', 'error') }
    finally { setSaving(false) }
  }

  const remove = async (id) => {
    if (!confirm('Delete this report?')) return
    try { await api.deleteReport(id); addToast('Deleted'); load() }
    catch { addToast('Failed', 'error') }
  }

  const downloadCSV = (type) => {
    const token = localStorage.getItem('pg_token')
    const url = `/api/reports/export/${type}.csv?days=30`
    const a = document.createElement('a')
    a.href = url
    a.setAttribute('download', `${type}_${Date.now()}.csv`)
    // Add token via header won't work for <a> download — need fetch approach
    fetch(url, { headers: { Authorization: `Bearer ${token}` } })
      .then(r => r.blob())
      .then(b => { a.href = URL.createObjectURL(b); document.body.appendChild(a); a.click(); a.remove() })
      .catch(() => addToast('Export failed', 'error'))
  }

  const columns = [
    { key: 'name', label: 'Report Name', render: v => <span style={{ fontWeight:600 }}>{v}</span> },
    { key: 'generatedBy', label: 'Generated By', render: v => <span style={{ color:'var(--accent)' }}>{v}</span> },
    { key: 'format', label: 'Format', render: v => <span style={{ fontFamily:'JetBrains Mono', fontSize:12, color:'var(--cyan)' }}>{v}</span> },
    { key: 'status', label: 'Status', render: v => (
      <span style={{ color: v==='completed' ? 'var(--green)' : 'var(--yellow)', fontWeight:700, fontSize:12 }}>{v?.toUpperCase()}</span>
    )},
    { key: 'date', label: 'Date', render: v => <span style={{ fontFamily:'JetBrains Mono', fontSize:11, color:'var(--text2)' }}>{v ? format(new Date(v), 'MM/dd/yyyy HH:mm') : '—'}</span> },
    { key: '_id', label: 'Actions', render: id => (
      <Btn onClick={() => remove(id)} variant="danger" style={{ padding:'4px 12px', fontSize:11 }}>Delete</Btn>
    )},
  ]

  return (
    <div>
      <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:24 }}>
        <div>
          <h1 style={{ fontSize:24, fontWeight:800, marginBottom:4 }}>Reports</h1>
          <div style={{ color:'var(--text2)', fontSize:13 }}>{reports.length} reports</div>
        </div>
        <div style={{ display:'flex', gap:10 }}>
          <Btn onClick={() => downloadCSV('events')} variant="ghost">⬇ Export Events CSV</Btn>
          <Btn onClick={() => downloadCSV('alerts')} variant="ghost">⬇ Export Alerts CSV</Btn>
          <Btn onClick={() => setModal(true)}>+ New Report</Btn>
        </div>
      </div>

      <div style={{ background:'var(--surface)', border:'1px solid var(--border)', borderRadius:12, overflow:'hidden' }}>
        {loading ? <Spinner /> : <Table columns={columns} data={reports} emptyMsg="No reports yet" />}
      </div>

      <Modal open={modal} onClose={() => setModal(false)} title="Create Report">
        <Input label="Report Name" value={form.name} onChange={e => setForm(f=>({...f,name:e.target.value}))} placeholder="Q2 Security Report" />
        <Input label="Generated By" value={form.generatedBy} onChange={e => setForm(f=>({...f,generatedBy:e.target.value}))} placeholder="Your name" />
        <Select label="Format" value={form.format} onChange={e => setForm(f=>({...f,format:e.target.value}))}>
          <option value="PDF">PDF</option>
          <option value="CSV">CSV</option>
          <option value="JSON">JSON</option>
          <option value="HTML">HTML</option>
        </Select>
        <div style={{ display:'flex', gap:10, justifyContent:'flex-end', marginTop:8 }}>
          <Btn variant="ghost" onClick={() => setModal(false)}>Cancel</Btn>
          <Btn onClick={create} loading={saving}>Create</Btn>
        </div>
      </Modal>
    </div>
  )
}
